{% set name = "tetgen" %}
{% set version = "1.5.1" %}
{% set sha256 = "51ff3af2cc05e18f4c8e15c46d07fd40fd57d1c40c9838b6d0533711f75ffdf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://wias-berlin.de/software/tetgen/1.5/src/tetgen{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - cmake >2.8  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

  run:

test:
  commands:
    - test -f ${PREFIX}/bin/tetgen  # [unix]
    - test -f ${PREFIX}/lib/libtet.a  # [unix]
    - test -f ${PREFIX}/include/tetgen.h  # [unix]

    - if not exist %LIBRARY_INC%\\tetgen.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\tet.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\tetgen.exe exit 1  # [win]

about:
  home: http://wias-berlin.de/software/tetgen
  license: AGPLv3
  license_file: LICENSE
  summary: 'A Quality Tetrahedral Mesh Generator and a 3D Delaunay Triangulator'

  description: |
    TetGen is a program to generate tetrahedral meshes of any 3D polyhedral
    domains. TetGen generates exact constrained Delaunay tetrahedralizations,
    boundary conforming Delaunay meshes, and Voronoi partitions.

extra:
  recipe-maintainers:
    - nehaljwani
    - cekees
    - msarahan
